name: Sorare Market Alert (Multi-Player)

on:
  workflow_dispatch:
  schedule:
    # Esegue il workflow ogni 5 minuti (frequenza massima)
    - cron: '*/5 * * * *'

jobs:
  check-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa dipendenze
        run: pip install requests

      - name: Esegui lo script di controllo mercato
        env:
          # --- CONFIGURA QUI LA TUA LISTA DI GIOCATORI ---
          # Formato JSON: facile da aggiungere, modificare o rimuovere giocatori.
          PLAYER_TARGETS_JSON: |
            [
              { "slug": "ederson-jose-dos-santos-lourenco-da-silva", "price": 1.4, "rarity": "limited" },
              { "slug": "jarrod-bowen", "price": 2.68, "rarity": "limited" }  
              { "slug": "martin-zlomislic", "price": 2.4, "rarity": "limited" }
            ]

          # --- SEGRETI DI GITHUB (rimangono uguali) ---
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SORARE_API_KEY: ${{ secrets.SORARE_API_KEY }}
        run: python market_alert.py
                - name: Commit and push notification state
              run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Aggiunge il file di stato solo se è stato modificato
          git add sent_notifications.json
          # Crea un commit solo se ci sono cambiamenti, altrimenti esce senza errori
          git commit -m "Aggiorna lo stato delle notifiche inviate" || exit 0
          # Spinge le modifiche al repository
          git push
