name: Sorare Market Alert (Multi-Player)
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
permissions:
  contents: write
jobs:
  check-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Installa dipendenze
        run: pip install requests gspread google-auth-oauthlib
      - name: Esegui lo script di controllo mercato
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SORARE_API_KEY: ${{ secrets.SORARE_API_KEY }}
          GSPREAD_CREDENTIALS: ${{ secrets.GSPREAD_CREDENTIALS }}
        run: python market_alert.py
      - name: Commit and push notification state
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if [ -f sent_notifications.json ]; then
            git add sent_notifications.json
            git commit -m "Aggiorna lo stato delle notifiche inviate" || exit 0
            git push
          else
            echo "Nessun file di stato da salvare."
          fi
