name: Sorare Market Alert (Multi-Player)

on:
  workflow_dispatch:
  schedule:
    # Esegue il workflow ogni 5 minuti (frequenza massima)
    - cron: '*/5 * * * *'

jobs:
  check-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa dipendenze
        run: pip install requests

      - name: Esegui lo script di controllo mercato
        env:
          # --- CONFIGURA QUI LA TUA LISTA DI GIOCATORI ---
          # Formato JSON: facile da aggiungere, modificare o rimuovere giocatori.
          PLAYER_TARGETS_JSON: |
            [
              { "slug": "erling-haaland", "price": 100, "rarity": "limited" },
              { "slug": "lionel-messi", "price": 55, "rarity": "rare" },
              { "slug": "kepa-arrizabalaga", "price": 1.5, "rarity": "limited" },
              { "slug": "cristiano-ronaldo", "price": 25, "rarity": "limited" }
            ]

          # --- SEGRETI DI GITHUB (rimangono uguali) ---
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SORARE_API_KEY: ${{ secrets.SORARE_API_KEY }}
        run: python market_alert.py
